# Generated by Django 5.1.6 on 2025-04-30 08:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('model_serial', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='模型编号')),
                ('name', models.CharField(max_length=40, verbose_name='名字')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('model_type', models.CharField(choices=[('obj', 'obj'), ('fbx', 'fbx'), ('gltf', 'gltf'), ('glb', 'glb'), ('mtl', 'mtl'), ('tga', 'tga')], default='gltf', max_length=10, verbose_name='模型类型')),
                ('model_state', models.CharField(choices=[('审核中', '审核中'), ('审核通过', '审核通过'), ('审核不通过', '审核不通过')], default='审核中', max_length=10, verbose_name='模型状态')),
                ('model_path', models.FileField(upload_to='', verbose_name='模型路径')),
                ('model_desc', models.CharField(blank=True, max_length=40, null=True, verbose_name='模型描述')),
                ('model_integral', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)], verbose_name='模型积分')),
            ],
            options={
                'verbose_name': '模型',
                'verbose_name_plural': '模型',
            },
        ),
        migrations.CreateModel(
            name='ModelStyle',
            fields=[
                ('style_serial', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='风格编号')),
                ('style_name', models.CharField(max_length=40, verbose_name='风格名称')),
            ],
            options={
                'verbose_name': '模型风格',
                'verbose_name_plural': '模型风格',
            },
        ),
        migrations.CreateModel(
            name='SignIn',
            fields=[
                ('integrationTask', models.AutoField(primary_key=True, serialize=False, verbose_name='签到任务编号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='任务创建时间')),
                ('integral', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)], verbose_name='签到积分')),
            ],
            options={
                'verbose_name': '签到任务',
                'verbose_name_plural': '签到任务',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_serial', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='用户编号')),
                ('username', models.CharField(max_length=40, unique=True, verbose_name='名字')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.CharField(choices=[('正常', '正常'), ('异常', '异常'), ('封号', '封号')], default='正常', max_length=10, verbose_name='状态')),
                ('integral', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000000)], verbose_name='积分')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.CreateModel(
            name='ModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to='', verbose_name='图片路径')),
                ('image_state', models.CharField(choices=[('审核中', '审核中'), ('审核通过', '审核通过'), ('审核不通过', '审核不通过')], default='审核中', max_length=10, verbose_name='图片状态')),
                ('model_serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='background.model', verbose_name='模型编号')),
            ],
            options={
                'verbose_name': '模型图片',
                'verbose_name_plural': '模型图片',
            },
        ),
        migrations.AddField(
            model_name='model',
            name='style_serial',
            field=models.ManyToManyField(related_name='models', to='background.modelstyle', verbose_name='模型风格'),
        ),
        migrations.AddField(
            model_name='model',
            name='user_serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='background.user', verbose_name='用户编号'),
        ),
        migrations.CreateModel(
            name='UserSignin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signin_time', models.DateTimeField(auto_now_add=True, verbose_name='签到时间')),
                ('state', models.CharField(choices=[('未签到', '未签到'), ('已签到', '已签到')], default='未签到', max_length=10, verbose_name='签到状态')),
                ('signin_integral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.signin', verbose_name='签到任务')),
                ('user_serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='background.user', verbose_name='用户编号')),
            ],
            options={
                'verbose_name': '用户签到',
                'verbose_name_plural': '用户签到',
            },
        ),
    ]
