# Generated by Django 5.1.6 on 2025-05-06 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0002_modelstyle_style_dsc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelimage',
            name='image_state',
        ),
    ]
