# Generated by Django 5.1.6 on 2025-05-13 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0003_remove_modelimage_image_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='model_path',
            field=models.FileField(max_length=500, upload_to='', verbose_name='模型路径'),
        ),
    ]
