# Generated by Django 5.1.6 on 2025-04-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelstyle',
            name='style_dsc',
            field=models.CharField(default='1', max_length=100, verbose_name='风格描述'),
        ),
    ]
